### ISSUE TITLE
status = get_status()["icestats"]["source"][index] KeyError

### ISSUE THREAD

**Issue by highon10kyears** [burritosoftware/Icecast-Scrobbler#1]
I'm running into this when attempting to invoke the script pointing to my own Icecast station— is this an issue with configuration on my server's end? I can't currently test whether the script works with Friday Night Tracks as originally designed, with the default URL in the .env-example, as they are currently off the air.

**Comment by burritosoftware** [comment]
Is your Icecast station updated? Try going to youricecasturl/status-json.xsl and seeing if you get a JSON output from it. Your Icecast server must be on 2.4.0 or later: xbn.fm (the station hosting Friday Night Tracks) is on a version that has this JSON format output.

If you do get an output, feel free to send that here (redacting any info if necessary), as well as a screeenshot of the error that appears in your terminal.

**Comment by highon10kyears** [comment]
I do get a JSON output, as the Icecast version I'm running is 2.4.99.3. Here's an example of my status-json output 
[status-json.xsl.json](https://github.com/burritosoftware/Icecast-Scrobbler/files/14255002/status-json.xsl.json)

Here's a screenshot of the full error:
![image](https://github.com/burritosoftware/Icecast-Scrobbler/assets/33668568/5592d83c-8430-444a-a254-3c7648754b67)

**Comment by burritosoftware** [comment]
Looks like this is an issue where your Icecast stream has only one source. For xbn.fm, they have multiple sources so I default to picking index 0 which is the first source. However, it looks like with your example output, since there's only one source, it doesn't know what to do about it. If you want, try editing the code to remove [index] and seeing if that'll help.

I'll try to push a fix for streams that only have one source, thanks for the catch!

**Comment by highon10kyears** [comment]
Removing [index] did the trick, thank you for the help!

**Comment by burritosoftware** [comment]
No prob! I'll push a proper fix for this as soon as I can.

**Comment by burritosoftware** [comment]
@highon10kyears Fixed in latest push, there's a new configuration option you can find in `.env-example` called multi source. Thanks again!
